# Generated by Django 5.0.6 on 2024-06-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='personal_info',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=100),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='degree',
            field=models.CharField(default='Unknown Degree', max_length=50),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='education_end_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='education_start_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='field_of_study',
            field=models.CharField(default='Unknown Field', max_length=50),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='job_description',
            field=models.TextField(default='No Description'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='job_end_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='job_start_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='job_title',
            field=models.CharField(default='Unknown Job', max_length=100),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='school_name',
            field=models.CharField(default='Unknown School', max_length=100),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
