# Generated by Django 5.0.6 on 2024-06-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_remove_experience_personal_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='certification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='certification_issuer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='certification_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='project_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='project_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='degree',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='education_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='education_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='field_of_study',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='job_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='job_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='job_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='school_name',
            field=models.CharField(max_length=100),
        ),
    ]
